# Generated by Django 3.2.14 on 2022-08-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
