# Generated by Django 3.2.14 on 2022-08-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
